spring:
  application:
    name: hr-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/vhr?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
# mybatis
myba/ tis:
   # mapper.xml文件所在的位置，对应在resources下面
  mapper-locations: classpath*:mapper/**/*.xml
  # 对应实体类的包名
  typeAliasesPackage: com.kxj.hrserver.*

# 日志
logging:
  level:
    com.kxj.hrserver: debug
    com.apache.ibatis: debug
    java.sql.Connection: debug
    java.sql.Statement: debug
    java.sql.PreparedStatement: debug
server:
  port: 8081


